import mongoose from 'mongoose';

const reflectionSchema = new mongoose.Schema(
  {
    // User who created the reflection
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },

    // Session this reflection belongs to
    session: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Session',
      required: true,
    },

    // User's original thought
    thought: {
      type: String,
      required: true,
      trim: true,
    },

    // AI detected cognitive distortion
    distortion: {
      type: String,
      default: '',
    },

    // Reason for the distortion
    barrier: {
      type: String,
      default: '',
    },

    // CBT technique selected by backend
    technique: {
      type: String,
      default: '',
    },

    // Personalized experiment generated by AI
    experiment: {
      type: String,
      default: '',
    },

    // User's reflection after completing experiment
    reflection: {
      type: String,
      default: '',
    },

    // AI generated balanced thought
    balancedThought: {
      type: String,
      default: '',
    },

    // Reflection completion status
    status: {
      type: String,
      enum: ['pending', 'completed'],
      default: 'pending',
    },
  },
  {
    timestamps: true,
  }
);

const Reflection = mongoose.model('Reflection', reflectionSchema);

export default Reflection;